Header header
float64 image_raw
float64 points_raw
float64 points_image
float64 vscan_points
float64 vscan_image
float64 image_obj
float64 image_obj_ranged
float64 image_obj_tracked
float64 current_pose
float64 obj_label
float64 cluster_centroids
float64 obj_pose
float64 execution_time
float64 cycle_time
float64 time_diff


# time image_raw
# time points_raw
# time image_obj
# time image_obj_ranged
# time image_obj_tracked
# time current_pose
# time obj_label
# time cluster_centroids
# time obj_pose