# https://github.com/git-lfs/git-lfs/wiki/Installation#debian-and-ubuntu
- name: Install Git LFS
  become: true
  ansible.builtin.apt:
    name: git-lfs
    state: latest
    update_cache: true

- name: Initialize Git LFS
  ansible.builtin.command: git lfs install
