name: docker-build-and-push
description: ""

inputs:
  name:
    description: ""
    required: true
  bake-target:
    description: ""
    required: true
  build-args:
    description: ""
    required: false
  tag-prefix:
    description: ""
    required: false
  tag-suffix:
    description: ""
    required: false

runs:
  using: composite
  steps:
    - name: Install jq and vcstool
      run: |
        sudo apt-get -y update
        sudo apt-get -y install jq python3-pip
        pip install --no-cache-dir vcstool
      shell: bash

    - name: Run vcs import
      run: |
        mkdir src
        vcs import src < autoware.repos
      shell: bash
    
    - name: Set up SSH
      uses: MrSquaare/ssh-setup-action@v3.1.0
      with:
        host: graviton-runner
        private-key: ${{ secrets.GRAVITON_RUNNER_SSH_KEY }}
        private-key-name: aws_graviton-runner

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64
        driver: docker-container
        append: |
          - endpoint: ssh://ubuntu@graviton-runner
            platforms: linux/arm64
            driver: docker-container

    - name: Restore ccache
      uses: actions/cache/restore@v4
      with:
        path: |
          root-ccache-amd64
          root-ccache-arm64
        key: ccache-${{ inputs.name }}-${{ hashFiles('src/**/*.cpp') }}
        restore-keys: |
          ccache-${{ inputs.name }}-
          ccache-

    - name: Restore apt-get
      uses: actions/cache/restore@v4
      with:
        path: |
          var-cache-apt-amd64
          var-cache-apt-arm64
        key: apt-get-${{ inputs.name }}-${{ hashFiles('src/**/package.xml') }}
        restore-keys: |
          apt-get-${{ inputs.name }}-
          apt-get-

    - name: Inject cache into docker
      uses: reproducible-containers/buildkit-cache-dance@v3.1.2
      with:
        cache-map: |
          {
            "root-ccache-amd64": "/root/.ccache",
            "root-ccache-arm64": "/root/.ccache",
            "var-cache-apt-amd64": "/var/cache/apt",
            "var-cache-apt-arm64": "/var/cache/apt"
          }
        skip-extraction: true

    - name: Set Docker tags
      id: set-docker-tags
      run: |
        tags=()
        if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref_type }}" == "tag" ]; then
            tags+=("$(echo "${{ github.ref }}" | sed -E 's/.*([vV][0-9]+\.[0-9]+\.[0-9]+).*/\1/')")
        fi

        tags+=("{{date 'YYYYMMDD'}}")
        tags+=("${{ inputs.tag-prefix }}")

        # Output multiline strings: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "tags<<$EOF" >> $GITHUB_OUTPUT
        echo "$(printf "%s\n" "${tags[@]}")" >> $GITHUB_OUTPUT
        echo "$EOF" >> $GITHUB_OUTPUT
      shell: bash

    - name: Docker meta for autoware:base
      id: meta-base
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-base
        flavor: |
          latest=false
          suffix=-base${{ inputs.tag-suffix }}

    - name: Docker meta for autoware:core-devel
      id: meta-core-devel
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-core-devel
        flavor: |
          latest=false
          suffix=-core-devel${{ inputs.tag-suffix }}

    - name: Docker meta for autoware:universe-sensing-perception-devel
      id: meta-universe-sensing-perception-devel
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-universe-sensing-perception-devel
        flavor: |
          latest=false
          suffix=-universe-sensing-perception-devel${{ inputs.tag-suffix }}

    - name: Docker meta for autoware:universe-sensing-perception
      id: meta-universe-sensing-perception
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-universe-sensing-perception
        flavor: |
          latest=false
          suffix=-universe-sensing-perception${{ inputs.tag-suffix }}

    - name: Docker meta for autoware:universe-localization-mapping-devel
      id: meta-universe-localization-mapping-devel
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-universe-localization-mapping-devel
        flavor: |
          latest=false
          suffix=-universe-localization-mapping-devel${{ inputs.tag-suffix }}

    - name: Docker meta for autoware:universe-localization-mapping
      id: meta-universe-localization-mapping
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-universe-localization-mapping
        flavor: |
          latest=false
          suffix=-universe-localization-mapping${{ inputs.tag-suffix }}

    - name: Docker meta for autoware:universe-planning-control-devel
      id: meta-universe-planning-control-devel
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-universe-planning-control-devel
        flavor: |
          latest=false
          suffix=-universe-planning-control-devel${{ inputs.tag-suffix }}

    - name: Docker meta for autoware:universe-planning-control
      id: meta-universe-planning-control
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-universe-planning-control
        flavor: |
          latest=false
          suffix=-universe-planning-control${{ inputs.tag-suffix }}

    - name: Docker meta for autoware:universe-devel
      id: meta-universe-devel
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-universe-devel
        flavor: |
          latest=false
          suffix=-universe-devel${{ inputs.tag-suffix }}

    - name: Docker meta for autoware:universe
      id: meta-universe
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-universe
        flavor: |
          latest=auto
          suffix=-universe${{ inputs.tag-suffix }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Build and Push to GitHub Container Registry
      uses: docker/bake-action@v5
      with:
        push: true
        files: |
          docker/docker-bake.hcl
          ${{ steps.meta-base.outputs.bake-file }}
          ${{ steps.meta-core-devel.outputs.bake-file }}
          ${{ steps.meta-universe-sensing-perception-devel.outputs.bake-file }}
          ${{ steps.meta-universe-sensing-perception.outputs.bake-file }}
          ${{ steps.meta-universe-localization-mapping-devel.outputs.bake-file }}
          ${{ steps.meta-universe-localization-mapping.outputs.bake-file }}
          ${{ steps.meta-universe-planning-control-devel.outputs.bake-file }}
          ${{ steps.meta-universe-planning-control.outputs.bake-file }}
          ${{ steps.meta-universe-devel.outputs.bake-file }}
          ${{ steps.meta-universe.outputs.bake-file }}
        provenance: false
        set: |
          ${{ inputs.build-args }}
