#!/bin/bash

set -e

. ./hooks/env 

if [[ "${LATEST_TAG}" =~ "ON" ]]; then
  # Tag and push image for latest tag
  docker tag ${DOCKER_REPO}:latest-synquacer-kinetic-rosdep ${DOCKER_REPO}:synquacer-kinetic-rosdep-${AUTOWARE_DOCKER_DATE}
  docker push ${DOCKER_REPO}:synquacer-kinetic-rosdep-${AUTOWARE_DOCKER_DATE}

  docker tag ${DOCKER_REPO}:latest-driveworks-kinetic-rosdep ${DOCKER_REPO}:driveworks-kinetic-rosdep-${AUTOWARE_DOCKER_DATE}
  docker push ${DOCKER_REPO}:driveworks-kinetic-rosdep-${AUTOWARE_DOCKER_DATE}
fi
