repos:
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v26.3.0
    hooks:
      - id: ansible-lint
        args:
          - ansible/
        additional_dependencies:
          - ansible
