# A sequence number is included to do primitive error checking
uint32 seq
geometry_msgs/PoseWithCovarianceStamped pose_with_covariance
---
bool success
uint32 seq
geometry_msgs/PoseWithCovarianceStamped pose_with_covariance
