- name: Install cuDNN and TensorRT
  become: true
  ansible.builtin.apt:
    name:
      - libcudnn8={{ cudnn_version }}
      - libcudnn8-dev={{ cudnn_version }}
      - tensorrt={{ tensorrt_version }}
    allow_downgrade: true
    update_cache: true

# apt-mark hold
- name: Prevent CUDA-related packages from upgrading
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - libcudnn8
    - libcudnn8-dev
    - tensorrt
