#!/usr/bin/env python3

# Copyright 2021 Tier IV, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import hashlib
import pathlib

from autoware_external_api_msgs.msg import MapHash
from autoware_external_api_msgs.msg import ResponseStatus
from autoware_external_api_msgs.srv import GetTextFile
import rclpy
from rclpy.node import Node
from rclpy.qos import QoSDurabilityPolicy
from rclpy.qos import QoSProfile


class MapHashGenerator(Node):
    def __init__(self):
        super().__init__("map_hash_generator")
        self.lanelet_path = self.declare_parameter("lanelet2_map_path", "").value
        self.lanelet_text = self.load_lanelet_text(self.lanelet_path)
        self.lanelet_hash = self.generate_file_hash(self.lanelet_text)

        qos_profile = QoSProfile(depth=1, durability=QoSDurabilityPolicy.TRANSIENT_LOCAL)
        msg = MapHash()
        msg.lanelet = self.lanelet_hash
        self.pub = self.create_publisher(MapHash, "/api/autoware/get/map/info/hash", qos_profile)
        self.pub.publish(msg)

        self.srv = self.create_service(
            GetTextFile, "/api/autoware/get/map/lanelet/xml", self.on_get_lanelet_xml
        )  # noqa: E501

    def on_get_lanelet_xml(self, request, response):
        response.status.code = ResponseStatus.SUCCESS
        response.file.text = self.lanelet_text
        return response

    @staticmethod
    def load_lanelet_text(path):
        path = pathlib.Path(path)
        return path.read_text() if path.is_file() else ""

    @staticmethod
    def generate_file_hash(data):
        return hashlib.sha256(data.encode()).hexdigest() if data else ""


def main(args=None):
    rclpy.init(args=args)
    node = MapHashGenerator()
    rclpy.spin(node)
    rclpy.shutdown()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
