- name: Get dash-case name of rmw_implementation
  ansible.builtin.shell: bash -c 'sed -e "s/_/-/g" <<< $(echo {{ rmw_implementation }})'
  register: rmw_implementation__dash_case_rmw_implementation
  changed_when: false

- name: Install ros-{{ rosdistro + '-' + rmw_implementation__dash_case_rmw_implementation.stdout }}
  become: true
  ansible.builtin.apt:
    name: ros-{{ rosdistro }}-{{ rmw_implementation__dash_case_rmw_implementation.stdout }}
    state: latest
    update_cache: true
  register: apt_install_result
  failed_when: "'Held packages were changed' not in apt_install_result.msg"

- name: Add RMW_IMPLEMENTATION to .bashrc
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: export RMW_IMPLEMENTATION={{ rmw_implementation }}
    state: present
    create: true
    mode: 0644
