#!/bin/bash

set -e

. ./hooks/env

# Parse image name for repo name
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

if [[ "${LATEST_TAG}" =~ "ON" ]]; then
  # Tag and push image for latest tag
  docker tag $IMAGE_NAME ${repoName}:latest-$ROS_DISTRO-cuda
  docker push ${repoName}:latest-$ROS_DISTRO-cuda
fi
