#!/usr/bin/env python3
# TODO(Takagi, Isamu): this is a temporary script and may change in the future
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("target", choices=["arch"])
parser.add_argument("format", choices=["full", "type", "version"], default="full", nargs="?")
args = parser.parse_args()
data = {"arch": {"type": "universe", "version": "1.0.0"}}

if args.format == "full":
    print("{type} {version}".format(**data[args.target]))
else:
    print(data[args.target][args.format])
