--- a/Makefile	2016-06-07 15:45:51.000000000 +0900
+++ b/Makefile	2016-09-27 00:00:00.879911251 +0900
@@ -37,6 +37,12 @@ MOVE          = mv -f
 CHK_DIR_EXISTS= test -d
 MKDIR         = mkdir -p
 
+AUTOWARE_CONFIG	= autoware_config
+AUTOWARE_CONFIG_PATH	= .
+
+AUTOWARE_SOCKET	= autoware_socket
+AUTOWARE_SOCKET_PATH	= ../../$(AUTOWARE_SOCKET)
+
 ####### Output directory
 
 OBJECTS_DIR   = ./
@@ -45,15 +51,16 @@ OBJECTS_DIR   = ./
 
 SOURCES       = main.cpp \
 		mainwindow.cpp \
-		RingBuffer.cpp \
 		HevCnt.cpp \
+		RingBuffer.cpp \
 		GameControl.cpp moc_mainwindow.cpp
 OBJECTS       = main.o \
 		mainwindow.o \
-		RingBuffer.o \
 		HevCnt.o \
+		RingBuffer.o \
 		GameControl.o \
-		moc_mainwindow.o
+		moc_mainwindow.o \
+		$(AUTOWARE_SOCKET).o
 DIST          = /usr/local/Trolltech/Qt-4.8.6/mkspecs/common/unix.conf \
 		/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/linux.conf \
 		/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base.conf \
@@ -172,7 +179,7 @@ qmake:  FORCE
 
 dist: 
 	@$(CHK_DIR_EXISTS) .tmp/HEV1.0.0 || $(MKDIR) .tmp/HEV1.0.0 
-	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/HEV1.0.0/ && $(COPY_FILE) --parents mainwindow.h RingBuffer.h HevCnt.h GameControl.h .tmp/HEV1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp RingBuffer.cpp HevCnt.cpp GameControl.cpp .tmp/HEV1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/HEV1.0.0/ && (cd `dirname .tmp/HEV1.0.0` && $(TAR) HEV1.0.0.tar HEV1.0.0 && $(COMPRESS) HEV1.0.0.tar) && $(MOVE) `dirname .tmp/HEV1.0.0`/HEV1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/HEV1.0.0
+	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/HEV1.0.0/ && $(COPY_FILE) --parents mainwindow.h HevCnt.h RingBuffer.h GameControl.h .tmp/HEV1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp HevCnt.cpp RingBuffer.cpp GameControl.cpp .tmp/HEV1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/HEV1.0.0/ && (cd `dirname .tmp/HEV1.0.0` && $(TAR) HEV1.0.0.tar HEV1.0.0 && $(COMPRESS) HEV1.0.0.tar) && $(MOVE) `dirname .tmp/HEV1.0.0`/HEV1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/HEV1.0.0
 
 
 clean:compiler_clean 
@@ -274,12 +281,11 @@ mainwindow.o: mainwindow.cpp mainwindow.
 		/usr/local/include/zmp/minivan/HevControlCommon.h \
 		/usr/local/include/zmp/minivan/CANUSB.h \
 		/usr/local/include/zmp/minivan/CANUSBConst.h \
-		ui_mainwindow.h
+		ui_mainwindow.h \
+		$(AUTOWARE_CONFIG_PATH)/autoware_config.h \
+		$(AUTOWARE_SOCKET_PATH)/autoware_socket.h
 	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp
 
-RingBuffer.o: RingBuffer.cpp RingBuffer.h
-	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RingBuffer.o RingBuffer.cpp
-
 HevCnt.o: HevCnt.cpp HevCnt.h \
 		/usr/local/include/zmp/minivan/HevControl.h \
 		/usr/local/include/zmp/minivan/DriveInformation.h \
@@ -296,6 +302,9 @@ HevCnt.o: HevCnt.cpp HevCnt.h \
 		/usr/local/include/zmp/minivan/CANUSBConst.h
 	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HevCnt.o HevCnt.cpp
 
+RingBuffer.o: RingBuffer.cpp RingBuffer.h
+	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RingBuffer.o RingBuffer.cpp
+
 GameControl.o: GameControl.cpp GameControl.h \
 		RingBuffer.h
 	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameControl.o GameControl.cpp
@@ -303,6 +312,17 @@ GameControl.o: GameControl.cpp GameContr
 moc_mainwindow.o: moc_mainwindow.cpp 
 	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp
 
+$(AUTOWARE_SOCKET).o:	$(AUTOWARE_SOCKET_PATH)/common.cpp \
+			$(AUTOWARE_SOCKET_PATH)/can.cpp \
+			$(AUTOWARE_SOCKET_PATH)/cmd.cpp \
+			$(AUTOWARE_SOCKET_PATH)/autoware_socket.h \
+			$(AUTOWARE_SOCKET_PATH)/drv.cpp \
+			$(AUTOWARE_SOCKET_PATH)/str.cpp \
+			$(AUTOWARE_CONFIG_PATH)/autoware_config.h \
+			mainwindow.h
+
+	$(CXX) -Wl,-r $(CXXFLAGS) $(INCPATH) $^ -o $(AUTOWARE_SOCKET).o -nostdlib
+
 ####### Install
 
 install:   FORCE
