#ifndef ERROR_CATEGORY_H_INCLUDED
#define ERROR_CATEGORY_H_INCLUDED

//#define MEMORY_ERROR 0
//#define SEGMENTATION_FAULT 2
#define EXCEPTION 2
#define NODE_IS_DEAD 3
#define LOW_SUBSCRIBE_RATE 4
#define LOW_PUBLISH_RATE 5
#define LOW_OPERATION_CYCLE 6
#define RESOURCE_NOT_FOUND 7
#define INVALID_INITIAL_VALUE 8
#define INVALID_VALUE 9
#define LOW_RELIABILITY 12
#define DEVICE_CONNECTION_LOST 13

#endif //ERROR_CATEGORY_H_INCLUDED