#ifndef __DECISION_MAKER_PARAM_HPP__
#define __DECISION_MAKER_PARAM_HPP__

namespace decision_maker
{
//#define DEBUG_PRINT

#define DEFAULT_DISPLAY_FLAG false
#define DEFAULT_FORCE_STATE_CHANGE true

#define VEL_AVERAGE_COUNT 10
#define DEFAULT_CONVERGENCE_COUNT 5
#define DEFAULT_CONVERGENCE_THRESHOLD 0.01

#define DOUBLE_MAX 1.7976931348623158e308
#define DEFAULT_TARGET_WAYPOINT 14

#define ANGLE_STRAIGHT 50.0
#define ANGLE_LEFT 360.0
#define ANGLE_RIGHT 180.0
}

#endif
