- name: Autoware development environment
  hosts: localhost
  connection: local
  vars:
    rosdistro:
    rmw_implementation:
    cuda_version:
    tensorrt_version:
    install_devel:
    cuda_install_drivers:
    spconv_version:
    cumm_version:
  pre_tasks:
    - name: Print configuration
      ansible.builtin.debug:
        msg:
          - rosdistro: "{{ rosdistro }}"
          - rmw_implementation: "{{ rmw_implementation }}"
          - cuda_version: "{{ cuda_version }}"
          - tensorrt_version: "{{ tensorrt_version }}"
          - install_devel: "{{ install_devel }}"
          - cuda_install_drivers: "{{ cuda_install_drivers }}"
          - spconv_version: "{{ spconv_version }}"
          - cumm_version: "{{ cumm_version }}"
      tags: [always]

  roles:
    - role: autoware.dev_env.rmw_implementation
      tags: [base, core, universe, rmw]
      vars:
        rmw_implementation__rosdistro: "{{ rosdistro }}"
        rmw_implementation__name: "{{ rmw_implementation }}"

    - role: autoware.dev_env.build_tools
      tags: [core, universe, ccache]

    - role: autoware.dev_env.dev_tools
      tags: [core, universe, dev_tools]

    - role: autoware.dev_env.ros2_dev_tools
      tags: [core, universe, ros2_dev_tools]

    - role: autoware.dev_env.acados
      tags: [universe, acados]

    - role: autoware.dev_env.geographiclib
      tags: [universe, geographiclib]

    - role: autoware.dev_env.qt5ct_setup
      tags: [universe, qt5ct_setup]

    - role: autoware.dev_env.cuda
      tags: [universe, nvidia, cuda]

    - role: autoware.dev_env.tensorrt
      tags: [universe, nvidia, tensorrt]

    - role: autoware.dev_env.spconv
      tags: [universe, nvidia, spconv]

    - role: autoware.dev_env.artifacts
      tags: [universe, artifacts]
