- hosts: localhost
  connection: local
  pre_tasks:
    - name: Verify OS
      ansible.builtin.shell: |
        if ! cat /etc/os-release | grep 'VERSION_ID="20.04"'; then
          echo 'Please use "Ubuntu 20.04".'
          exit 1
        fi

    - name: Print args
      ansible.builtin.debug:
        msg:
          - rosdistro: "{{ rosdistro }}"
          - rmw_implementation: "{{ rmw_implementation }}"
  roles:
    - role: autoware.dev_env.autoware_core
    - role: autoware.dev_env.ccache
    - role: autoware.dev_env.plotjuggler
    - role: autoware.dev_env.pre_commit
    - role: autoware.dev_env.ros2
    - role: autoware.dev_env.ros2_dev_tools
    - role: autoware.dev_env.rmw_implementation
