#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Wed Feb  4 21:57:47 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
	def __init__(self, *args, **kwds):
		# begin wxGlade: MyFrame.__init__
		kwds["style"] = wx.DEFAULT_FRAME_STYLE
		wx.Frame.__init__(self, *args, **kwds)
		self.notebook_1 = wx.Notebook(self, wx.ID_ANY, style=0)
		self.notebook_1_pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
		self.label_5_copy = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("Mobile IP"))
		self.label_6_copy = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("Tablet IP"))
		self.label_7_copy = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("Vehicle IP"))
		self.label_7_copy_copy = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("Database IP"))
		self.text_ctrl_ip_a_0 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.label_4_copy_4 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("."))
		self.text_ctrl_ip_a_1 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.label_4_copy_copy_2 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("."))
		self.text_ctrl_ip_a_2 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.label_4_copy_1_copy_2 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("."))
		self.text_ctrl_ip_a_3 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.text_ctrl_ip_b_0 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.label_4_copy_5 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("."))
		self.text_ctrl_ip_b_1 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.label_4_copy_copy_3 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("."))
		self.text_ctrl_ip_b_2 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.label_4_copy_1_copy_3 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("."))
		self.text_ctrl_ip_b_3 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.text_ctrl_ip_c_0 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.label_4_copy_6 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("."))
		self.text_ctrl_ip_c_1 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.label_4_copy_copy_4 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("."))
		self.text_ctrl_ip_c_2 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.label_4_copy_1_copy_4 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("."))
		self.text_ctrl_ip_c_3 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.text_ctrl_ip_d_0 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.label_4_copy_6_copy = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("."))
		self.text_ctrl_ip_d_1 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.label_4_copy_copy_4_copy = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("."))
		self.text_ctrl_ip_d_2 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.label_4_copy_1_copy_4_copy = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("."))
		self.text_ctrl_ip_d_3 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.button_conn_a = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Listen"))
		self.button_conn_b = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Listen"))
		self.button_conn_c = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Listen"))
		self.button_conn_d = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Listen"))
		self.button_disconn_a = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Terminate"))
		self.button_disconn_b = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Terminate"))
		self.button_disconn_c = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Terminate"))
		self.button_disconn_d = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Terminate"))
		self.label_1 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("State Check"))
		self.button_statchk_d = wx.ToggleButton(self.notebook_1_pane_1, wx.ID_ANY, _("D"))
		self.button_statchk_r = wx.ToggleButton(self.notebook_1_pane_1, wx.ID_ANY, _("R"))
		self.button_statchk_b = wx.ToggleButton(self.notebook_1_pane_1, wx.ID_ANY, _("B"))
		self.button_statchk_n = wx.ToggleButton(self.notebook_1_pane_1, wx.ID_ANY, _("N"))
		self.button_statchk_prog = wx.ToggleButton(self.notebook_1_pane_1, wx.ID_ANY, _("Program"))
		self.button_statchk_manu = wx.ToggleButton(self.notebook_1_pane_1, wx.ID_ANY, _("Manual"))
		self.label_13_copy = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("Accel"))
		self.label_14_copy = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("Brake"))
		self.label_15_copy = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("Steer"))
		self.slider_statchk_accel = wx.Slider(self.notebook_1_pane_1, wx.ID_ANY, 0, 0, 100)
		self.slider_statchk_brake = wx.Slider(self.notebook_1_pane_1, wx.ID_ANY, 0, 0, 100)
		self.slider_statchk_steer = wx.Slider(self.notebook_1_pane_1, wx.ID_ANY, 0, -120, 120)
		self.label_11 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("Veloc"))
		self.slider_statchk_veloc = wx.Slider(self.notebook_1_pane_1, wx.ID_ANY, 0, 0, 300)
		self.label_12 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("Indicator"))
		self.button_statchk_indi_l = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("L"))
		self.button_statchk_indi_r = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("R"))
		self.sizer_6_staticbox = wx.StaticBox(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.label_16 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("Route to"))
		self.text_ctrl_route_to_lat = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.text_ctrl_route_to_lon = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.label_17 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("from"))
		self.text_ctrl_route_from_lat = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.text_ctrl_route_from_lon = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.button_map = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Map"))
		self.label_error = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("Errors : 0"))
		self.sizer_18_staticbox = wx.StaticBox(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.label_mode = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("Mode : P"))
		self.sizer_19_staticbox = wx.StaticBox(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.label_gear = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("Gear : D"))
		self.sizer_20_staticbox = wx.StaticBox(self.notebook_1_pane_1, wx.ID_ANY, "")
		self.button_start = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Start"))
		self.button_stop = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, _("Stop"))
		self.label_21_copy = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, _("Autoware v1.0"))
		self.bitmap_1 = wx.StaticBitmap(self.notebook_1_pane_1, wx.ID_ANY, wx.NullBitmap)
		self.bitmap_2 = wx.StaticBitmap(self.notebook_1_pane_1, wx.ID_ANY, wx.NullBitmap)
		self.notebook_1_pane_2 = wx.Panel(self.notebook_1, wx.ID_ANY)
		self.notebook_1_pane_3 = wx.Panel(self.notebook_1, wx.ID_ANY)
		self.tree_ctrl_0 = wx.TreeCtrl(self.notebook_1_pane_3, wx.ID_ANY, style=wx.TR_HAS_BUTTONS | wx.TR_NO_LINES | wx.TR_DEFAULT_STYLE | wx.SUNKEN_BORDER)
		self.tree_ctrl_1 = wx.TreeCtrl(self.notebook_1_pane_3, wx.ID_ANY, style=wx.TR_HAS_BUTTONS | wx.TR_NO_LINES | wx.TR_DEFAULT_STYLE | wx.SUNKEN_BORDER)
		self.tree_ctrl_2 = wx.TreeCtrl(self.notebook_1_pane_3, wx.ID_ANY, style=wx.TR_HAS_BUTTONS | wx.TR_NO_LINES | wx.TR_DEFAULT_STYLE | wx.SUNKEN_BORDER)
		self.notebook_1_pane_4 = wx.Panel(self.notebook_1, wx.ID_ANY)
		self.label_2 = wx.StaticText(self.notebook_1_pane_4, wx.ID_ANY, _("Area:"))
		self.text_ctrl_moving_objects_route_to_lat = wx.TextCtrl(self.notebook_1_pane_4, wx.ID_ANY, "")
		self.text_ctrl_moving_objects_route_to_lon = wx.TextCtrl(self.notebook_1_pane_4, wx.ID_ANY, "")
		self.label_3 = wx.StaticText(self.notebook_1_pane_4, wx.ID_ANY, _("-"))
		self.text_ctrl_moving_objects_route_from_lat = wx.TextCtrl(self.notebook_1_pane_4, wx.ID_ANY, "")
		self.text_ctrl_moving_objects_route_from_lon = wx.TextCtrl(self.notebook_1_pane_4, wx.ID_ANY, "")
		self.button_moving_objects = wx.ToggleButton(self.notebook_1_pane_4, wx.ID_ANY, _("Moving Objects"))
		self.notebook_1_pane_5 = wx.Panel(self.notebook_1, wx.ID_ANY)
		self.panel_sensing = wx.ScrolledWindow(self.notebook_1_pane_5, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
		self.checkbox_auto_probe = wx.CheckBox(self.notebook_1_pane_5, wx.ID_ANY, _("Auto Probe"))
		self.button_probe = wx.Button(self.notebook_1_pane_5, wx.ID_ANY, _("Probe"))
		self.button_calibration = wx.ToggleButton(self.notebook_1_pane_5, wx.ID_ANY, _("Calibration"))
		self.sizer_24_staticbox = wx.StaticBox(self.notebook_1_pane_5, wx.ID_ANY, "")
		self.text_ctrl_tf = wx.TextCtrl(self.notebook_1_pane_5, wx.ID_ANY, "")
		self.button_ref_tf = wx.Button(self.notebook_1_pane_5, wx.ID_ANY, _("Ref"))
		self.button_launch_tf = wx.Button(self.notebook_1_pane_5, wx.ID_ANY, _("TF"))
		self.button_kill_tf = wx.Button(self.notebook_1_pane_5, wx.ID_ANY, _("Kill"))
		self.sizer_25_staticbox = wx.StaticBox(self.notebook_1_pane_5, wx.ID_ANY, "")
		self.text_ctrl_sensor_fusion = wx.TextCtrl(self.notebook_1_pane_5, wx.ID_ANY, "")
		self.button_ref_sensor_fusion = wx.Button(self.notebook_1_pane_5, wx.ID_ANY, _("Ref"))
		self.button_launch_sensor_fusion = wx.Button(self.notebook_1_pane_5, wx.ID_ANY, _("Sensor Fusion"))
		self.button_kill_sensor_fusion = wx.Button(self.notebook_1_pane_5, wx.ID_ANY, _("Kill"))
		self.sizer_25_copy_staticbox = wx.StaticBox(self.notebook_1_pane_5, wx.ID_ANY, "")
		self.text_ctrl_rosbag_record = wx.TextCtrl(self.notebook_1_pane_5, wx.ID_ANY, "")
		self.button_ref_rosbag_record = wx.Button(self.notebook_1_pane_5, wx.ID_ANY, _("Ref"))
		self.button_launch_rosbag_record = wx.Button(self.notebook_1_pane_5, wx.ID_ANY, _("ROSBAG Record"))
		self.button_kill_rosbag_record = wx.Button(self.notebook_1_pane_5, wx.ID_ANY, _("Kill"))
		self.sizer_25_copy_1_staticbox = wx.StaticBox(self.notebook_1_pane_5, wx.ID_ANY, "")
		self.tab_simulation = wx.Panel(self.notebook_1, wx.ID_ANY)
		self.panel_simulation = wx.ScrolledWindow(self.tab_simulation, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
		self.checkbox_point_map_update = wx.CheckBox(self.tab_simulation, wx.ID_ANY, _("Point Map Update"))
		self.panel_3 = wx.ScrolledWindow(self.tab_simulation, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
		self.text_ctrl_rosbag_play = wx.TextCtrl(self.panel_3, wx.ID_ANY, "")
		self.button_ref_rosbag_play = wx.Button(self.panel_3, wx.ID_ANY, _("Ref"))
		self.button_launch_rosbag_play = wx.Button(self.panel_3, wx.ID_ANY, _("ROSBAG Play"))
		self.button_kill_rosbag_play = wx.Button(self.panel_3, wx.ID_ANY, _("Kill"))
		self.sizer_25_copy_copy_staticbox = wx.StaticBox(self.panel_3, wx.ID_ANY, "")
		self.text_ctrl_rosbag_play_clock = wx.TextCtrl(self.panel_3, wx.ID_ANY, "")
		self.button_ref_rosbag_play_clock = wx.Button(self.panel_3, wx.ID_ANY, _("Ref"))
		self.button_launch_rosbag_play_clock = wx.Button(self.panel_3, wx.ID_ANY, _("ROSBAG Play (CLOCK)"))
		self.button_kill_rosbag_play_clock = wx.Button(self.panel_3, wx.ID_ANY, _("Kill"))
		self.sizer_25_copy_copy_copy_1_staticbox = wx.StaticBox(self.panel_3, wx.ID_ANY, "")
		self.text_ctrl_pmap = wx.TextCtrl(self.panel_3, wx.ID_ANY, "")
		self.button_ref_pmap = wx.Button(self.panel_3, wx.ID_ANY, _("Ref"))
		self.button_launch_pmap = wx.Button(self.panel_3, wx.ID_ANY, _("Point Map"))
		self.button_kill_pmap = wx.Button(self.panel_3, wx.ID_ANY, _("Kill"))
		self.sizer_25_copy_copy_copy_staticbox = wx.StaticBox(self.panel_3, wx.ID_ANY, "")
		self.text_ctrl_vmap = wx.TextCtrl(self.panel_3, wx.ID_ANY, "")
		self.button_ref_vmap = wx.Button(self.panel_3, wx.ID_ANY, _("Ref"))
		self.button_launch_vmap = wx.Button(self.panel_3, wx.ID_ANY, _("Vector Map"))
		self.button_kill_vmap = wx.Button(self.panel_3, wx.ID_ANY, _("Kill"))
		self.sizer_25_copy_copy_copy_copy_staticbox = wx.StaticBox(self.panel_3, wx.ID_ANY, "")
		self.text_ctrl_trajectory = wx.TextCtrl(self.panel_3, wx.ID_ANY, "")
		self.button_ref_trajectory = wx.Button(self.panel_3, wx.ID_ANY, _("Ref"))
		self.button_launch_trajectory = wx.Button(self.panel_3, wx.ID_ANY, _("Trajectory"))
		self.button_kill_trajectory = wx.Button(self.panel_3, wx.ID_ANY, _("Kill"))
		self.sizer_25_copy_copy_copy_copy_copy_copy_staticbox = wx.StaticBox(self.panel_3, wx.ID_ANY, "")
		self.tab_viewer = wx.Panel(self.notebook_1, wx.ID_ANY)
		self.panel_viewer = wx.ScrolledWindow(self.tab_viewer, wx.ID_ANY, style=wx.TAB_TRAVERSAL)

		self.__set_properties()
		self.__do_layout()

		self.Bind(wx.EVT_TEXT, self.OnTextIp, self.text_ctrl_ip_a_0)
		self.Bind(wx.EVT_TEXT, self.OnTextIp, self.text_ctrl_ip_a_1)
		self.Bind(wx.EVT_TEXT, self.OnTextIp, self.text_ctrl_ip_a_2)
		self.Bind(wx.EVT_TEXT, self.OnTextIp, self.text_ctrl_ip_a_3)
		self.Bind(wx.EVT_TEXT, self.OnTextIp, self.text_ctrl_ip_b_0)
		self.Bind(wx.EVT_TEXT, self.OnTextIp, self.text_ctrl_ip_b_1)
		self.Bind(wx.EVT_TEXT, self.OnTextIp, self.text_ctrl_ip_b_2)
		self.Bind(wx.EVT_TEXT, self.OnTextIp, self.text_ctrl_ip_b_3)
		self.Bind(wx.EVT_TEXT, self.OnTextIp, self.text_ctrl_ip_c_0)
		self.Bind(wx.EVT_TEXT, self.OnTextIp, self.text_ctrl_ip_c_1)
		self.Bind(wx.EVT_TEXT, self.OnTextIp, self.text_ctrl_ip_c_2)
		self.Bind(wx.EVT_TEXT, self.OnTextIp, self.text_ctrl_ip_c_3)
		self.Bind(wx.EVT_TEXT, self.OnTextIp, self.text_ctrl_ip_d_0)
		self.Bind(wx.EVT_TEXT, self.OnTextIp, self.text_ctrl_ip_d_1)
		self.Bind(wx.EVT_TEXT, self.OnTextIp, self.text_ctrl_ip_d_2)
		self.Bind(wx.EVT_TEXT, self.OnTextIp, self.text_ctrl_ip_d_3)
		self.Bind(wx.EVT_BUTTON, self.OnConn, self.button_conn_a)
		self.Bind(wx.EVT_BUTTON, self.OnConn, self.button_conn_b)
		self.Bind(wx.EVT_BUTTON, self.OnConn, self.button_conn_c)
		self.Bind(wx.EVT_BUTTON, self.OnConn, self.button_conn_d)
		self.Bind(wx.EVT_BUTTON, self.OnDisconn, self.button_disconn_a)
		self.Bind(wx.EVT_BUTTON, self.OnDisconn, self.button_disconn_b)
		self.Bind(wx.EVT_BUTTON, self.OnDisconn, self.button_disconn_c)
		self.Bind(wx.EVT_BUTTON, self.OnDisconn, self.button_disconn_d)
		self.Bind(wx.EVT_TOGGLEBUTTON, self.OnGear, self.button_statchk_d)
		self.Bind(wx.EVT_TOGGLEBUTTON, self.OnGear, self.button_statchk_r)
		self.Bind(wx.EVT_TOGGLEBUTTON, self.OnGear, self.button_statchk_b)
		self.Bind(wx.EVT_TOGGLEBUTTON, self.OnGear, self.button_statchk_n)
		self.Bind(wx.EVT_TOGGLEBUTTON, self.OnProgManu, self.button_statchk_prog)
		self.Bind(wx.EVT_TOGGLEBUTTON, self.OnProgManu, self.button_statchk_manu)
		self.Bind(wx.EVT_COMMAND_SCROLL, self.OnScAccel, self.slider_statchk_accel)
		self.Bind(wx.EVT_COMMAND_SCROLL, self.OnScBrake, self.slider_statchk_brake)
		self.Bind(wx.EVT_COMMAND_SCROLL, self.OnScSteer, self.slider_statchk_steer)
		self.Bind(wx.EVT_COMMAND_SCROLL, self.OnScVeloc, self.slider_statchk_veloc)
		self.Bind(wx.EVT_BUTTON, self.OnIndi, self.button_statchk_indi_l)
		self.Bind(wx.EVT_BUTTON, self.OnIndi, self.button_statchk_indi_r)
		self.Bind(wx.EVT_TEXT, self.OnTextRoute, self.text_ctrl_route_to_lat)
		self.Bind(wx.EVT_TEXT, self.OnTextRoute, self.text_ctrl_route_to_lon)
		self.Bind(wx.EVT_TEXT, self.OnTextRoute, self.text_ctrl_route_from_lat)
		self.Bind(wx.EVT_TEXT, self.OnTextRoute, self.text_ctrl_route_from_lon)
		self.Bind(wx.EVT_BUTTON, self.OnMap, self.button_map)
		self.Bind(wx.EVT_BUTTON, self.OnStart, self.button_start)
		self.Bind(wx.EVT_BUTTON, self.OnStop, self.button_stop)
		self.Bind(wx.EVT_TEXT, self.OnTextArea, self.text_ctrl_moving_objects_route_to_lat)
		self.Bind(wx.EVT_TEXT, self.OnTextArea, self.text_ctrl_moving_objects_route_to_lon)
		self.Bind(wx.EVT_TEXT, self.OnTextArea, self.text_ctrl_moving_objects_route_from_lat)
		self.Bind(wx.EVT_TEXT, self.OnTextArea, self.text_ctrl_moving_objects_route_from_lon)
		self.Bind(wx.EVT_TOGGLEBUTTON, self.OnMovingObjects, self.button_moving_objects)
		self.Bind(wx.EVT_CHECKBOX, self.OnAutoProbe, self.checkbox_auto_probe)
		self.Bind(wx.EVT_BUTTON, self.OnProbe, self.button_probe)
		self.Bind(wx.EVT_TOGGLEBUTTON, self.OnCalib, self.button_calibration)
		self.Bind(wx.EVT_BUTTON, self.OnRef, self.button_ref_tf)
		self.Bind(wx.EVT_BUTTON, self.OnLaunch, self.button_launch_tf)
		self.Bind(wx.EVT_BUTTON, self.OnKill, self.button_kill_tf)
		self.Bind(wx.EVT_BUTTON, self.OnRef, self.button_ref_sensor_fusion)
		self.Bind(wx.EVT_BUTTON, self.OnLaunch, self.button_launch_sensor_fusion)
		self.Bind(wx.EVT_BUTTON, self.OnKill, self.button_kill_sensor_fusion)
		self.Bind(wx.EVT_BUTTON, self.OnRef, self.button_ref_rosbag_record)
		self.Bind(wx.EVT_BUTTON, self.OnLaunch, self.button_launch_rosbag_record)
		self.Bind(wx.EVT_BUTTON, self.OnKill, self.button_kill_rosbag_record)
		self.Bind(wx.EVT_CHECKBOX, self.OnPointMapUpdate, self.checkbox_point_map_update)
		self.Bind(wx.EVT_BUTTON, self.OnRef, self.button_ref_rosbag_play)
		self.Bind(wx.EVT_BUTTON, self.OnLaunch, self.button_launch_rosbag_play)
		self.Bind(wx.EVT_BUTTON, self.OnKill, self.button_kill_rosbag_play)
		self.Bind(wx.EVT_BUTTON, self.OnRef, self.button_ref_rosbag_play_clock)
		self.Bind(wx.EVT_BUTTON, self.OnLaunch, self.button_launch_rosbag_play_clock)
		self.Bind(wx.EVT_BUTTON, self.OnKill, self.button_kill_rosbag_play_clock)
		self.Bind(wx.EVT_BUTTON, self.OnRef, self.button_ref_pmap)
		self.Bind(wx.EVT_BUTTON, self.OnLaunch, self.button_launch_pmap)
		self.Bind(wx.EVT_BUTTON, self.OnKill, self.button_kill_pmap)
		self.Bind(wx.EVT_BUTTON, self.OnRef, self.button_ref_vmap)
		self.Bind(wx.EVT_BUTTON, self.OnLaunch, self.button_launch_vmap)
		self.Bind(wx.EVT_BUTTON, self.OnKill, self.button_kill_vmap)
		self.Bind(wx.EVT_BUTTON, self.OnRef, self.button_ref_trajectory)
		self.Bind(wx.EVT_BUTTON, self.OnLaunch, self.button_launch_trajectory)
		self.Bind(wx.EVT_BUTTON, self.OnKill, self.button_kill_trajectory)
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: MyFrame.__set_properties
		self.SetTitle(_("runtime manager"))
		self.button_conn_a.Enable(False)
		self.button_conn_b.Enable(False)
		self.button_conn_c.Enable(False)
		self.button_conn_d.Enable(False)
		self.button_disconn_a.Enable(False)
		self.button_disconn_b.Enable(False)
		self.button_disconn_c.Enable(False)
		self.button_disconn_d.Enable(False)
		self.button_statchk_d.SetMinSize((29, 29))
		self.button_statchk_r.SetMinSize((29, 29))
		self.button_statchk_b.SetMinSize((29, 29))
		self.button_statchk_b.SetValue(1)
		self.button_statchk_n.SetMinSize((29, 29))
		self.button_statchk_manu.SetValue(1)
		self.slider_statchk_accel.SetMinSize((82, 27))
		self.slider_statchk_brake.SetMinSize((82, 27))
		self.slider_statchk_steer.SetMinSize((82, 27))
		self.button_statchk_indi_l.SetMinSize((29, 29))
		self.button_statchk_indi_r.SetMinSize((29, 29))
		self.label_21_copy.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
		self.button_moving_objects.Enable(False)
		self.panel_sensing.SetScrollRate(10, 10)
		self.checkbox_auto_probe.Hide()
		self.button_ref_tf.SetMinSize((40, 29))
		self.button_kill_tf.SetMinSize((40, 29))
		self.button_kill_tf.Enable(False)
		self.button_ref_sensor_fusion.SetMinSize((40, 29))
		self.button_kill_sensor_fusion.SetMinSize((40, 29))
		self.button_kill_sensor_fusion.Enable(False)
		self.button_ref_rosbag_record.SetMinSize((40, 29))
		self.button_kill_rosbag_record.SetMinSize((40, 29))
		self.button_kill_rosbag_record.Enable(False)
		self.panel_simulation.SetScrollRate(10, 10)
		self.button_ref_rosbag_play.SetMinSize((40, 29))
		self.button_kill_rosbag_play.SetMinSize((40, 29))
		self.button_kill_rosbag_play.Enable(False)
		self.button_ref_rosbag_play_clock.SetMinSize((40, 29))
		self.button_kill_rosbag_play_clock.SetMinSize((40, 29))
		self.button_kill_rosbag_play_clock.Enable(False)
		self.button_ref_pmap.SetMinSize((40, 29))
		self.button_kill_pmap.SetMinSize((40, 29))
		self.button_kill_pmap.Enable(False)
		self.button_ref_vmap.SetMinSize((40, 29))
		self.button_kill_vmap.SetMinSize((40, 29))
		self.button_kill_vmap.Enable(False)
		self.button_ref_trajectory.SetMinSize((40, 29))
		self.button_kill_trajectory.SetMinSize((40, 29))
		self.button_kill_trajectory.Enable(False)
		self.panel_3.SetMinSize((250, -1))
		self.panel_3.SetScrollRate(10, 10)
		self.panel_viewer.SetMinSize((366, 390))
		self.panel_viewer.SetScrollRate(10, 10)
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: MyFrame.__do_layout
		self.sizer_1 = wx.BoxSizer(wx.VERTICAL)
		sizer_26 = wx.BoxSizer(wx.HORIZONTAL)
		self.sizer_viewer = wx.BoxSizer(wx.VERTICAL)
		sizer_5_copy = wx.BoxSizer(wx.HORIZONTAL)
		sizer_7_copy = wx.BoxSizer(wx.VERTICAL)
		self.sizer_25_copy_copy_copy_copy_copy_copy_staticbox.Lower()
		sizer_25_copy_copy_copy_copy_copy_copy = wx.StaticBoxSizer(self.sizer_25_copy_copy_copy_copy_copy_copy_staticbox, wx.VERTICAL)
		sizer_8_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
		sizer_28_copy_copy_copy_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
		self.sizer_25_copy_copy_copy_copy_staticbox.Lower()
		sizer_25_copy_copy_copy_copy = wx.StaticBoxSizer(self.sizer_25_copy_copy_copy_copy_staticbox, wx.VERTICAL)
		sizer_8_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
		sizer_28_copy_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
		self.sizer_25_copy_copy_copy_staticbox.Lower()
		sizer_25_copy_copy_copy = wx.StaticBoxSizer(self.sizer_25_copy_copy_copy_staticbox, wx.VERTICAL)
		sizer_8_copy = wx.BoxSizer(wx.HORIZONTAL)
		sizer_28_copy_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
		self.sizer_25_copy_copy_copy_1_staticbox.Lower()
		sizer_25_copy_copy_copy_1 = wx.StaticBoxSizer(self.sizer_25_copy_copy_copy_1_staticbox, wx.VERTICAL)
		sizer_8_copy_2 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_28_copy_copy_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
		self.sizer_25_copy_copy_staticbox.Lower()
		sizer_25_copy_copy = wx.StaticBoxSizer(self.sizer_25_copy_copy_staticbox, wx.VERTICAL)
		sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_28_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
		sizer_9 = wx.BoxSizer(wx.VERTICAL)
		sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_7 = wx.BoxSizer(wx.VERTICAL)
		self.sizer_25_copy_1_staticbox.Lower()
		sizer_25_copy_1 = wx.StaticBoxSizer(self.sizer_25_copy_1_staticbox, wx.VERTICAL)
		sizer_8_copy_1_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_28_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
		self.sizer_25_copy_staticbox.Lower()
		sizer_25_copy = wx.StaticBoxSizer(self.sizer_25_copy_staticbox, wx.VERTICAL)
		sizer_8_copy_1_copy = wx.BoxSizer(wx.HORIZONTAL)
		sizer_28_copy = wx.BoxSizer(wx.HORIZONTAL)
		self.sizer_25_staticbox.Lower()
		sizer_25 = wx.StaticBoxSizer(self.sizer_25_staticbox, wx.VERTICAL)
		sizer_8_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_28 = wx.BoxSizer(wx.HORIZONTAL)
		self.sizer_24_staticbox.Lower()
		sizer_24 = wx.StaticBoxSizer(self.sizer_24_staticbox, wx.HORIZONTAL)
		sizer_23 = wx.BoxSizer(wx.VERTICAL)
		sizer_23_copy_1 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_27 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_4 = wx.BoxSizer(wx.VERTICAL)
		sizer_2 = wx.BoxSizer(wx.VERTICAL)
		sizer_26_copy = wx.BoxSizer(wx.HORIZONTAL)
		sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
		self.sizer_20_staticbox.Lower()
		sizer_20 = wx.StaticBoxSizer(self.sizer_20_staticbox, wx.HORIZONTAL)
		self.sizer_19_staticbox.Lower()
		sizer_19 = wx.StaticBoxSizer(self.sizer_19_staticbox, wx.HORIZONTAL)
		self.sizer_18_staticbox.Lower()
		sizer_18 = wx.StaticBoxSizer(self.sizer_18_staticbox, wx.HORIZONTAL)
		sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
		self.sizer_6_staticbox.Lower()
		sizer_6 = wx.StaticBoxSizer(self.sizer_6_staticbox, wx.HORIZONTAL)
		sizer_10 = wx.BoxSizer(wx.VERTICAL)
		sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_15_copy = wx.BoxSizer(wx.VERTICAL)
		sizer_14_copy = wx.BoxSizer(wx.VERTICAL)
		sizer_32 = wx.BoxSizer(wx.VERTICAL)
		sizer_34 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_33 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_21 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_22_copy_2 = wx.BoxSizer(wx.VERTICAL)
		sizer_22_copy_1 = wx.BoxSizer(wx.VERTICAL)
		sizer_22_copy = wx.BoxSizer(wx.VERTICAL)
		sizer_4_copy_4_copy = wx.BoxSizer(wx.HORIZONTAL)
		sizer_4_copy_4 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_4_copy_3 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_4_copy_2 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_22 = wx.BoxSizer(wx.VERTICAL)
		sizer_22.Add(self.label_5_copy, 1, 0, 0)
		sizer_22.Add(self.label_6_copy, 1, 0, 0)
		sizer_22.Add(self.label_7_copy, 1, 0, 0)
		sizer_22.Add(self.label_7_copy_copy, 1, 0, 0)
		sizer_21.Add(sizer_22, 0, wx.EXPAND, 0)
		sizer_4_copy_2.Add(self.text_ctrl_ip_a_0, 0, 0, 0)
		sizer_4_copy_2.Add(self.label_4_copy_4, 0, 0, 0)
		sizer_4_copy_2.Add(self.text_ctrl_ip_a_1, 0, 0, 0)
		sizer_4_copy_2.Add(self.label_4_copy_copy_2, 0, 0, 0)
		sizer_4_copy_2.Add(self.text_ctrl_ip_a_2, 0, 0, 0)
		sizer_4_copy_2.Add(self.label_4_copy_1_copy_2, 0, 0, 0)
		sizer_4_copy_2.Add(self.text_ctrl_ip_a_3, 0, 0, 0)
		sizer_22_copy.Add(sizer_4_copy_2, 1, wx.EXPAND, 0)
		sizer_4_copy_3.Add(self.text_ctrl_ip_b_0, 0, 0, 0)
		sizer_4_copy_3.Add(self.label_4_copy_5, 0, 0, 0)
		sizer_4_copy_3.Add(self.text_ctrl_ip_b_1, 0, 0, 0)
		sizer_4_copy_3.Add(self.label_4_copy_copy_3, 0, 0, 0)
		sizer_4_copy_3.Add(self.text_ctrl_ip_b_2, 0, 0, 0)
		sizer_4_copy_3.Add(self.label_4_copy_1_copy_3, 0, 0, 0)
		sizer_4_copy_3.Add(self.text_ctrl_ip_b_3, 0, 0, 0)
		sizer_22_copy.Add(sizer_4_copy_3, 1, wx.EXPAND, 0)
		sizer_4_copy_4.Add(self.text_ctrl_ip_c_0, 0, 0, 0)
		sizer_4_copy_4.Add(self.label_4_copy_6, 0, 0, 0)
		sizer_4_copy_4.Add(self.text_ctrl_ip_c_1, 0, 0, 0)
		sizer_4_copy_4.Add(self.label_4_copy_copy_4, 0, 0, 0)
		sizer_4_copy_4.Add(self.text_ctrl_ip_c_2, 0, 0, 0)
		sizer_4_copy_4.Add(self.label_4_copy_1_copy_4, 0, 0, 0)
		sizer_4_copy_4.Add(self.text_ctrl_ip_c_3, 0, 0, 0)
		sizer_22_copy.Add(sizer_4_copy_4, 1, wx.EXPAND, 0)
		sizer_4_copy_4_copy.Add(self.text_ctrl_ip_d_0, 0, 0, 0)
		sizer_4_copy_4_copy.Add(self.label_4_copy_6_copy, 0, 0, 0)
		sizer_4_copy_4_copy.Add(self.text_ctrl_ip_d_1, 0, 0, 0)
		sizer_4_copy_4_copy.Add(self.label_4_copy_copy_4_copy, 0, 0, 0)
		sizer_4_copy_4_copy.Add(self.text_ctrl_ip_d_2, 0, 0, 0)
		sizer_4_copy_4_copy.Add(self.label_4_copy_1_copy_4_copy, 0, 0, 0)
		sizer_4_copy_4_copy.Add(self.text_ctrl_ip_d_3, 0, 0, 0)
		sizer_22_copy.Add(sizer_4_copy_4_copy, 1, wx.EXPAND, 0)
		sizer_21.Add(sizer_22_copy, 0, wx.EXPAND, 0)
		sizer_22_copy_1.Add(self.button_conn_a, 1, 0, 0)
		sizer_22_copy_1.Add(self.button_conn_b, 1, 0, 0)
		sizer_22_copy_1.Add(self.button_conn_c, 1, 0, 0)
		sizer_22_copy_1.Add(self.button_conn_d, 1, 0, 0)
		sizer_21.Add(sizer_22_copy_1, 0, wx.EXPAND, 0)
		sizer_22_copy_2.Add(self.button_disconn_a, 1, wx.EXPAND, 0)
		sizer_22_copy_2.Add(self.button_disconn_b, 1, wx.EXPAND, 0)
		sizer_22_copy_2.Add(self.button_disconn_c, 1, wx.EXPAND, 0)
		sizer_22_copy_2.Add(self.button_disconn_d, 1, wx.EXPAND, 0)
		sizer_21.Add(sizer_22_copy_2, 1, wx.EXPAND, 0)
		sizer_2.Add(sizer_21, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.EXPAND, 4)
		sizer_3.Add(self.label_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		sizer_33.Add(self.button_statchk_d, 1, wx.EXPAND, 0)
		sizer_33.Add(self.button_statchk_r, 1, wx.EXPAND, 0)
		sizer_33.Add(self.button_statchk_b, 1, wx.EXPAND, 0)
		sizer_33.Add(self.button_statchk_n, 1, wx.EXPAND, 0)
		sizer_32.Add(sizer_33, 1, wx.EXPAND, 0)
		sizer_34.Add(self.button_statchk_prog, 1, wx.EXPAND, 0)
		sizer_34.Add(self.button_statchk_manu, 1, wx.EXPAND, 0)
		sizer_32.Add(sizer_34, 1, wx.EXPAND, 0)
		sizer_6.Add(sizer_32, 0, wx.EXPAND, 0)
		sizer_14_copy.Add(self.label_13_copy, 1, 0, 0)
		sizer_14_copy.Add(self.label_14_copy, 1, 0, 0)
		sizer_14_copy.Add(self.label_15_copy, 1, 0, 0)
		sizer_6.Add(sizer_14_copy, 0, wx.LEFT | wx.EXPAND, 4)
		sizer_15_copy.Add(self.slider_statchk_accel, 0, wx.EXPAND | wx.ALIGN_CENTER_VERTICAL, 0)
		sizer_15_copy.Add(self.slider_statchk_brake, 0, wx.EXPAND | wx.ALIGN_CENTER_VERTICAL, 0)
		sizer_15_copy.Add(self.slider_statchk_steer, 0, wx.EXPAND | wx.ALIGN_CENTER_VERTICAL, 0)
		sizer_6.Add(sizer_15_copy, 1, wx.EXPAND, 0)
		sizer_11.Add(self.label_11, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		sizer_11.Add(self.slider_statchk_veloc, 1, wx.ALIGN_CENTER_VERTICAL, 0)
		sizer_10.Add(sizer_11, 1, wx.LEFT | wx.EXPAND, 2)
		sizer_12.Add(self.label_12, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		sizer_12.Add(self.button_statchk_indi_l, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		sizer_12.Add(self.button_statchk_indi_r, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		sizer_10.Add(sizer_12, 1, wx.LEFT | wx.EXPAND, 4)
		sizer_6.Add(sizer_10, 1, wx.EXPAND, 0)
		sizer_3.Add(sizer_6, 1, wx.EXPAND, 0)
		sizer_2.Add(sizer_3, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.EXPAND, 4)
		sizer_16.Add(self.label_16, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		sizer_16.Add(self.text_ctrl_route_to_lat, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		sizer_16.Add(self.text_ctrl_route_to_lon, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		sizer_16.Add(self.label_17, 0, wx.LEFT | wx.ALIGN_CENTER_VERTICAL, 4)
		sizer_16.Add(self.text_ctrl_route_from_lat, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		sizer_16.Add(self.text_ctrl_route_from_lon, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		sizer_16.Add(self.button_map, 1, wx.LEFT | wx.ALIGN_CENTER_VERTICAL, 4)
		sizer_2.Add(sizer_16, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.EXPAND, 4)
		sizer_18.Add(self.label_error, 0, 0, 0)
		sizer_17.Add(sizer_18, 1, wx.EXPAND, 0)
		sizer_19.Add(self.label_mode, 0, 0, 0)
		sizer_17.Add(sizer_19, 1, wx.EXPAND, 0)
		sizer_20.Add(self.label_gear, 0, 0, 0)
		sizer_17.Add(sizer_20, 1, wx.EXPAND, 0)
		sizer_17.Add(self.button_start, 0, wx.EXPAND, 0)
		sizer_17.Add(self.button_stop, 0, wx.EXPAND, 0)
		sizer_2.Add(sizer_17, 1, wx.ALL | wx.EXPAND, 4)
		sizer_26_copy.Add(self.label_21_copy, 0, wx.LEFT | wx.ALIGN_CENTER_VERTICAL, 4)
		sizer_26_copy.Add(self.bitmap_1, 0, wx.LEFT | wx.ALIGN_CENTER_VERTICAL, 20)
		sizer_26_copy.Add(self.bitmap_2, 0, wx.LEFT | wx.ALIGN_CENTER_VERTICAL, 20)
		sizer_2.Add(sizer_26_copy, 0, wx.EXPAND, 0)
		self.notebook_1_pane_1.SetSizer(sizer_2)
		self.notebook_1_pane_2.SetSizer(sizer_4)
		sizer_27.Add(self.tree_ctrl_0, 1, wx.EXPAND, 0)
		sizer_27.Add(self.tree_ctrl_1, 1, wx.EXPAND, 0)
		sizer_27.Add(self.tree_ctrl_2, 1, wx.EXPAND, 0)
		self.notebook_1_pane_3.SetSizer(sizer_27)
		sizer_23_copy_1.Add(self.label_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)
		sizer_23_copy_1.Add(self.text_ctrl_moving_objects_route_to_lat, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 4)
		sizer_23_copy_1.Add(self.text_ctrl_moving_objects_route_to_lon, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 4)
		sizer_23_copy_1.Add(self.label_3, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 4)
		sizer_23_copy_1.Add(self.text_ctrl_moving_objects_route_from_lat, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 4)
		sizer_23_copy_1.Add(self.text_ctrl_moving_objects_route_from_lon, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 4)
		sizer_23_copy_1.Add(self.button_moving_objects, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 4)
		sizer_23.Add(sizer_23_copy_1, 0, wx.ALL | wx.EXPAND, 4)
		self.notebook_1_pane_4.SetSizer(sizer_23)
		sizer_5.Add(self.panel_sensing, 1, wx.EXPAND, 0)
		sizer_24.Add(self.checkbox_auto_probe, 0, wx.LEFT | wx.TOP | wx.BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 4)
		sizer_24.Add(self.button_probe, 0, wx.LEFT | wx.TOP | wx.BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 4)
		sizer_24.Add(self.button_calibration, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL, 4)
		sizer_7.Add(sizer_24, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.EXPAND, 4)
		sizer_28.Add(self.text_ctrl_tf, 1, wx.LEFT | wx.TOP, 4)
		sizer_28.Add(self.button_ref_tf, 0, wx.LEFT | wx.RIGHT | wx.TOP, 4)
		sizer_25.Add(sizer_28, 1, wx.EXPAND, 0)
		sizer_8_copy_1.Add(self.button_launch_tf, 0, wx.ALL, 4)
		sizer_8_copy_1.Add(self.button_kill_tf, 0, wx.ALL, 4)
		sizer_25.Add(sizer_8_copy_1, 1, wx.EXPAND, 0)
		sizer_7.Add(sizer_25, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.EXPAND, 4)
		sizer_28_copy.Add(self.text_ctrl_sensor_fusion, 1, wx.LEFT | wx.TOP, 4)
		sizer_28_copy.Add(self.button_ref_sensor_fusion, 0, wx.LEFT | wx.RIGHT | wx.TOP, 4)
		sizer_25_copy.Add(sizer_28_copy, 1, wx.EXPAND, 0)
		sizer_8_copy_1_copy.Add(self.button_launch_sensor_fusion, 0, wx.ALL, 4)
		sizer_8_copy_1_copy.Add(self.button_kill_sensor_fusion, 0, wx.ALL, 4)
		sizer_25_copy.Add(sizer_8_copy_1_copy, 1, wx.EXPAND, 0)
		sizer_7.Add(sizer_25_copy, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.EXPAND, 4)
		sizer_28_copy_1.Add(self.text_ctrl_rosbag_record, 1, wx.LEFT | wx.TOP, 4)
		sizer_28_copy_1.Add(self.button_ref_rosbag_record, 0, wx.LEFT | wx.RIGHT | wx.TOP, 4)
		sizer_25_copy_1.Add(sizer_28_copy_1, 1, wx.EXPAND, 0)
		sizer_8_copy_1_copy_1.Add(self.button_launch_rosbag_record, 0, wx.ALL, 4)
		sizer_8_copy_1_copy_1.Add(self.button_kill_rosbag_record, 0, wx.ALL, 4)
		sizer_25_copy_1.Add(sizer_8_copy_1_copy_1, 1, wx.EXPAND, 0)
		sizer_7.Add(sizer_25_copy_1, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.EXPAND, 4)
		sizer_5.Add(sizer_7, 0, wx.LEFT | wx.EXPAND, 4)
		self.notebook_1_pane_5.SetSizer(sizer_5)
		sizer_9.Add(self.panel_simulation, 1, wx.EXPAND, 0)
		sizer_9.Add(self.checkbox_point_map_update, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
		sizer_5_copy.Add(sizer_9, 1, wx.EXPAND, 0)
		sizer_28_copy_copy.Add(self.text_ctrl_rosbag_play, 1, wx.LEFT | wx.TOP, 4)
		sizer_28_copy_copy.Add(self.button_ref_rosbag_play, 0, wx.LEFT | wx.RIGHT | wx.TOP, 4)
		sizer_25_copy_copy.Add(sizer_28_copy_copy, 0, wx.EXPAND, 0)
		sizer_8.Add(self.button_launch_rosbag_play, 0, wx.ALL, 4)
		sizer_8.Add(self.button_kill_rosbag_play, 0, wx.ALL, 4)
		sizer_25_copy_copy.Add(sizer_8, 1, wx.EXPAND, 0)
		sizer_7_copy.Add(sizer_25_copy_copy, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.EXPAND, 4)
		sizer_28_copy_copy_copy_1.Add(self.text_ctrl_rosbag_play_clock, 1, wx.LEFT | wx.TOP, 4)
		sizer_28_copy_copy_copy_1.Add(self.button_ref_rosbag_play_clock, 0, wx.LEFT | wx.RIGHT | wx.TOP, 4)
		sizer_25_copy_copy_copy_1.Add(sizer_28_copy_copy_copy_1, 0, wx.EXPAND, 0)
		sizer_8_copy_2.Add(self.button_launch_rosbag_play_clock, 0, wx.ALL, 4)
		sizer_8_copy_2.Add(self.button_kill_rosbag_play_clock, 0, wx.ALL, 4)
		sizer_25_copy_copy_copy_1.Add(sizer_8_copy_2, 1, wx.EXPAND, 0)
		sizer_7_copy.Add(sizer_25_copy_copy_copy_1, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.EXPAND, 4)
		sizer_28_copy_copy_copy.Add(self.text_ctrl_pmap, 1, wx.LEFT | wx.TOP, 4)
		sizer_28_copy_copy_copy.Add(self.button_ref_pmap, 0, wx.LEFT | wx.RIGHT | wx.TOP, 4)
		sizer_25_copy_copy_copy.Add(sizer_28_copy_copy_copy, 0, wx.EXPAND, 0)
		sizer_8_copy.Add(self.button_launch_pmap, 0, wx.ALL, 4)
		sizer_8_copy.Add(self.button_kill_pmap, 0, wx.ALL, 4)
		sizer_25_copy_copy_copy.Add(sizer_8_copy, 1, wx.EXPAND, 0)
		sizer_7_copy.Add(sizer_25_copy_copy_copy, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.EXPAND, 4)
		sizer_28_copy_copy_copy_copy.Add(self.text_ctrl_vmap, 1, wx.LEFT | wx.TOP, 4)
		sizer_28_copy_copy_copy_copy.Add(self.button_ref_vmap, 0, wx.LEFT | wx.RIGHT | wx.TOP, 4)
		sizer_25_copy_copy_copy_copy.Add(sizer_28_copy_copy_copy_copy, 0, wx.EXPAND, 0)
		sizer_8_copy_copy.Add(self.button_launch_vmap, 0, wx.ALL, 4)
		sizer_8_copy_copy.Add(self.button_kill_vmap, 0, wx.ALL, 4)
		sizer_25_copy_copy_copy_copy.Add(sizer_8_copy_copy, 1, wx.EXPAND, 0)
		sizer_7_copy.Add(sizer_25_copy_copy_copy_copy, 0, wx.LEFT | wx.RIGHT | wx.TOP | wx.EXPAND, 4)
		sizer_28_copy_copy_copy_copy_copy_copy.Add(self.text_ctrl_trajectory, 1, wx.LEFT | wx.TOP, 4)
		sizer_28_copy_copy_copy_copy_copy_copy.Add(self.button_ref_trajectory, 0, wx.LEFT | wx.RIGHT | wx.TOP, 4)
		sizer_25_copy_copy_copy_copy_copy_copy.Add(sizer_28_copy_copy_copy_copy_copy_copy, 0, wx.EXPAND, 0)
		sizer_8_copy_copy_copy.Add(self.button_launch_trajectory, 0, wx.ALL, 4)
		sizer_8_copy_copy_copy.Add(self.button_kill_trajectory, 0, wx.ALL, 4)
		sizer_25_copy_copy_copy_copy_copy_copy.Add(sizer_8_copy_copy_copy, 1, wx.EXPAND, 0)
		sizer_7_copy.Add(sizer_25_copy_copy_copy_copy_copy_copy, 0, wx.ALL | wx.EXPAND, 4)
		self.panel_3.SetSizer(sizer_7_copy)
		sizer_5_copy.Add(self.panel_3, 0, wx.EXPAND, 0)
		self.tab_simulation.SetSizer(sizer_5_copy)
		self.panel_viewer.SetSizer(self.sizer_viewer)
		sizer_26.Add(self.panel_viewer, 1, wx.EXPAND, 0)
		sizer_26.Add((20, 20), 1, 0, 0)
		self.tab_viewer.SetSizer(sizer_26)
		self.notebook_1.AddPage(self.notebook_1_pane_1, _("Main"))
		self.notebook_1.AddPage(self.notebook_1_pane_2, _("Actuation"))
		self.notebook_1.AddPage(self.notebook_1_pane_3, _("Computing"))
		self.notebook_1.AddPage(self.notebook_1_pane_4, _("Database"))
		self.notebook_1.AddPage(self.notebook_1_pane_5, _("Sensing"))
		self.notebook_1.AddPage(self.tab_simulation, _("Simulation"))
		self.notebook_1.AddPage(self.tab_viewer, _("Viewer"))
		self.sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
		self.SetSizer(self.sizer_1)
		self.sizer_1.Fit(self)
		self.Layout()
		# end wxGlade

	def OnTextIp(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnTextIp' not implemented!"
		event.Skip()

	def OnConn(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnConn' not implemented!"
		event.Skip()

	def OnDisconn(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnDisconn' not implemented!"
		event.Skip()

	def OnGear(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnGear' not implemented!"
		event.Skip()

	def OnProgManu(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnProgManu' not implemented!"
		event.Skip()

	def OnScAccel(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnScAccel' not implemented!"
		event.Skip()

	def OnScBrake(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnScBrake' not implemented!"
		event.Skip()

	def OnScSteer(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnScSteer' not implemented!"
		event.Skip()

	def OnScVeloc(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnScVeloc' not implemented!"
		event.Skip()

	def OnIndi(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnIndi' not implemented!"
		event.Skip()

	def OnTextRoute(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnTextRoute' not implemented!"
		event.Skip()

	def OnMap(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnMap' not implemented!"
		event.Skip()

	def OnStart(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnStart' not implemented!"
		event.Skip()

	def OnStop(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnStop' not implemented!"
		event.Skip()

	def OnTextArea(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnTextArea' not implemented!"
		event.Skip()

	def OnMovingObjects(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnMovingObjects' not implemented!"
		event.Skip()

	def OnAutoProbe(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnAutoProbe' not implemented!"
		event.Skip()

	def OnProbe(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnProbe' not implemented!"
		event.Skip()

	def OnCalib(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnCalib' not implemented!"
		event.Skip()

	def OnRef(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnRef' not implemented!"
		event.Skip()

	def OnLaunch(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnLaunch' not implemented!"
		event.Skip()

	def OnKill(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnKill' not implemented!"
		event.Skip()

	def OnPointMapUpdate(self, event):  # wxGlade: MyFrame.<event_handler>
		print "Event handler 'OnPointMapUpdate' not implemented!"
		event.Skip()

# end of class MyFrame

class MyDialog(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: MyDialog.__init__
		kwds["style"] = wx.DEFAULT_DIALOG_STYLE
		wx.Dialog.__init__(self, *args, **kwds)
		self.panel_2 = wx.ScrolledWindow(self, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
		self.radio_box = wx.RadioBox(self.panel_2, wx.ID_ANY, "", choices=[_("0"), _("1"), _("2"), _("3")], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
		self.button_1 = wx.Button(self, wx.ID_ANY, _("OK"))
		self.button_1_copy = wx.Button(self, wx.ID_ANY, _("Cancel"))

		self.__set_properties()
		self.__do_layout()

		self.Bind(wx.EVT_BUTTON, self.OnOk, self.button_1)
		self.Bind(wx.EVT_BUTTON, self.OnCancel, self.button_1_copy)
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: MyDialog.__set_properties
		self.SetSize((258, 212))
		self.radio_box.SetSelection(0)
		self.panel_2.SetScrollRate(10, 10)
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: MyDialog.__do_layout
		sizer_13 = wx.BoxSizer(wx.VERTICAL)
		sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_14.Add(self.radio_box, 1, wx.LEFT | wx.RIGHT | wx.TOP | wx.ALIGN_CENTER_HORIZONTAL, 4)
		self.panel_2.SetSizer(sizer_14)
		sizer_13.Add(self.panel_2, 1, wx.EXPAND, 0)
		sizer_15.Add(self.button_1, 0, wx.ALL, 4)
		sizer_15.Add(self.button_1_copy, 0, wx.ALL, 4)
		sizer_13.Add(sizer_15, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
		self.SetSizer(sizer_13)
		self.Layout()
		# end wxGlade

	def OnOk(self, event):  # wxGlade: MyDialog.<event_handler>
		print "Event handler 'OnOk' not implemented!"
		event.Skip()

	def OnCancel(self, event):  # wxGlade: MyDialog.<event_handler>
		print "Event handler 'OnCancel' not implemented!"
		event.Skip()

# end of class MyDialog

class MyDialogPath(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: MyDialogPath.__init__
		kwds["style"] = wx.DEFAULT_DIALOG_STYLE
		wx.Dialog.__init__(self, *args, **kwds)
		self.text_ctrl = wx.TextCtrl(self, wx.ID_ANY, "")
		self.button_ref_rosbag_simu = wx.Button(self, wx.ID_ANY, _("Ref"))
		self.button_1 = wx.Button(self, wx.ID_ANY, _("OK"))
		self.button_1_copy = wx.Button(self, wx.ID_ANY, _("Cancel"))

		self.__set_properties()
		self.__do_layout()

		self.Bind(wx.EVT_BUTTON, self.OnRef, self.button_ref_rosbag_simu)
		self.Bind(wx.EVT_BUTTON, self.OnOk, self.button_1)
		self.Bind(wx.EVT_BUTTON, self.OnCancel, self.button_1_copy)
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: MyDialogPath.__set_properties
		self.SetTitle(_("dialog_2"))
		self.SetSize((482, 145))
		self.button_ref_rosbag_simu.SetMinSize((40, 29))
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: MyDialogPath.__do_layout
		sizer_30 = wx.BoxSizer(wx.VERTICAL)
		sizer_31 = wx.BoxSizer(wx.HORIZONTAL)
		sizer_28_copy_copy = wx.BoxSizer(wx.HORIZONTAL)
		sizer_28_copy_copy.Add(self.text_ctrl, 1, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 4)
		sizer_28_copy_copy.Add(self.button_ref_rosbag_simu, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 4)
		sizer_30.Add(sizer_28_copy_copy, 1, wx.EXPAND, 0)
		sizer_31.Add(self.button_1, 0, wx.ALL, 4)
		sizer_31.Add(self.button_1_copy, 0, wx.ALL, 4)
		sizer_30.Add(sizer_31, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
		self.SetSizer(sizer_30)
		self.Layout()
		# end wxGlade

	def OnRef(self, event):  # wxGlade: MyDialogPath.<event_handler>
		print "Event handler 'OnRef' not implemented!"
		event.Skip()

	def OnOk(self, event):  # wxGlade: MyDialogPath.<event_handler>
		print "Event handler 'OnOk' not implemented!"
		event.Skip()

	def OnCancel(self, event):  # wxGlade: MyDialogPath.<event_handler>
		print "Event handler 'OnCancel' not implemented!"
		event.Skip()

# end of class MyDialogPath

class MyDialogParam(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: MyDialogParam.__init__
		kwds["style"] = wx.DEFAULT_DIALOG_STYLE
		wx.Dialog.__init__(self, *args, **kwds)
		self.panel_v = wx.ScrolledWindow(self, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
		self.button_1 = wx.Button(self, wx.ID_ANY, _("OK"))
		self.button_1_copy = wx.Button(self, wx.ID_ANY, _("Cancel"))

		self.__set_properties()
		self.__do_layout()

		self.Bind(wx.EVT_BUTTON, self.OnOk, self.button_1)
		self.Bind(wx.EVT_BUTTON, self.OnCancel, self.button_1_copy)
		# end wxGlade

	def __set_properties(self):
		# begin wxGlade: MyDialogParam.__set_properties
		self.SetTitle(_("dialog_3"))
		self.SetSize((470, 246))
		self.panel_v.SetScrollRate(10, 10)
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: MyDialogParam.__do_layout
		sizer_30 = wx.BoxSizer(wx.VERTICAL)
		sizer_31 = wx.BoxSizer(wx.HORIZONTAL)
		self.sizer_v = wx.BoxSizer(wx.VERTICAL)
		self.panel_v.SetSizer(self.sizer_v)
		sizer_30.Add(self.panel_v, 1, wx.EXPAND, 0)
		sizer_31.Add(self.button_1, 0, wx.ALL, 4)
		sizer_31.Add(self.button_1_copy, 0, wx.ALL, 4)
		sizer_30.Add(sizer_31, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
		self.SetSizer(sizer_30)
		self.Layout()
		# end wxGlade

	def OnOk(self, event):  # wxGlade: MyDialogParam.<event_handler>
		print "Event handler 'OnOk' not implemented!"
		event.Skip()

	def OnCancel(self, event):  # wxGlade: MyDialogParam.<event_handler>
		print "Event handler 'OnCancel' not implemented!"
		event.Skip()

# end of class MyDialogParam
class MyApp(wx.App):
	def OnInit(self):
		wx.InitAllImageHandlers()
		frame_1 = MyFrame(None, wx.ID_ANY, "")
		self.SetTopWindow(frame_1)
		frame_1.Show()
		return 1

# end of class MyApp

if __name__ == "__main__":
	gettext.install("app") # replace with the appropriate catalog name

	app = MyApp(0)
	app.MainLoop()