DROP TABLE IF EXISTS "candata";

CREATE TABLE "candata"
(
  timestamp             timestamp NOT NULL,
  startup               timestamp NOT NULL,
  terminal              character(17) NOT NULL,
  can_str               double precision,
  can_vel               double precision,
  can_gas               double precision,
  can_brake             double precision,
  can_seatbelt          double precision,
  can_water_temperature double precision,
  acc_x                 double precision,
  acc_y                 double precision,
  acc_z                 double precision,
  lat                   double precision,
  lon                   double precision,
  roll                  double precision,
  pitch                 double precision,
  yaw                   double precision,
  img                   text,
  cal_orientation_x     double precision,
  cal_orientation_y     double precision,
  cal_orientation_z     double precision,
  gravity_x             double precision,
  gravity_y             double precision,
  gravity_z             double precision,
  gyroscope_x           double precision,
  gyroscope_y           double precision,
  gyroscope_z           double precision,
  light                 double precision,
  linear_acc_x          double precision,
  linear_acc_y          double precision,
  linear_acc_z          double precision,
  magnetic_field_x      double precision,
  magnetic_field_y      double precision,
  magnetic_field_z      double precision,
  orientation_x         double precision,
  orientation_y         double precision,
  orientation_z         double precision,
  pressure              double precision,
  proximity             double precision,
  rotation_vector_x     double precision,
  rotation_vector_y     double precision,
  rotation_vector_z     double precision,
  rotation_vector_c     double precision,
  temperature           double precision,
  ambient_temperature   double precision,
  relative_humidity     double precision,
  bearing               double precision,
  altitude              double precision,
  accuracy              double precision,
  speed                 double precision,
  env_battery           double precision,
  env_temperature       double precision,
  PRIMARY KEY (timestamp, startup, terminal)
)
WITH (
  OIDS=FALSE
);
