#!/usr/bin/env bash
set -e

echo "This script is deprecated and will be removed soon, please use colcon_release instead"
sleep 2

if [[ -d build ]]; then
    rm -rf build
fi

if [[ -d devel ]]; then
    rm -rf devel
fi

CATKIN_OPTS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs"

catkin_make clean $CATKIN_OPTS
source devel/setup.bash

export LIBRARY_PATH=/usr/lib/OpenNI2/Drivers:$LIBRARY_PATH
catkin_make $CATKIN_OPTS $@
