#!/usr/bin/env bash

PROC_MANAGERS=$(ps aux |\grep "proc_manager.py"|\grep -v grep |awk '{print $2}')
if [[ $PROC_MANAGERS == "" ]]; then
    exit 0
fi

if [[ $UID != 0 ]]; then
    echo "Please input password for cleanup"    
    sudo kill $PROC_MANAGERS
else
    kill $PROC_MANAGERS
fi
