#! /usr/bin/env python

import subprocess

roscore_command = "roscore"
manager_command = "rosrun autoware_launcher main"

def gnome_terminal(command):
    return ["gnome-terminal", "--command", command]

# Add source command
roscore_command = "bash -c 'source ./install/setup.bash; {}'".format(roscore_command)
manager_command = "bash -c 'source ./install/setup.bash; {}'".format(manager_command)

# Launch terminals
subprocess.call(gnome_terminal(roscore_command))
subprocess.call(gnome_terminal(manager_command))

