//#define GEAR_DRIVE 1
#define GEAR_DRIVE 16
#define GEAR_REAR 2
#define GEAR_BREAK 3
#define GEAR_NEUTRAL 4
#define GEAR_PARKING 5

#define MIN_BRAKE_VALUE 0
#define MAX_BRAKE_VALUE 4095

#define MIN_ACCEL_VALUE 0
#define MAX_ACCEL_VALUE 4095