name: health-check-pr

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - id: check
        uses: step-security/changed-files@v47
        with:
          files: |
            repositories/*.repos
            .github/workflows/health-check.yaml
            .github/workflows/health-check-pr.yaml
            .github/workflows/health-check-reusable.yaml
            ansible-galaxy-requirements.yaml
            ansible/**
            docker/**
          files_ignore: |
            docker/examples/**
            **/*.md

  require-label:
    needs: changed-files
    if: needs.changed-files.outputs.should-run == 'true'
    uses: autowarefoundation/autoware-github-actions/.github/workflows/require-label.yaml@v1
    with:
      label: run:health-check

  health-check:
    if: ${{ always() }}
    needs: [changed-files, require-label]
    strategy:
      fail-fast: false
      matrix:
        build-type: [main, nightly, main-arm64]
        include:
          - build-type: main
            platform: amd64
            runner: "['ubuntu-24.04']"
          - build-type: nightly
            platform: amd64
            runner: "['ubuntu-24.04']"
          - build-type: main-arm64
            platform: arm64
            runner: "['ubuntu-24.04-arm']"
    uses: ./.github/workflows/health-check-reusable.yaml
    with:
      build-type: ${{ matrix.build-type }}
      platform: ${{ matrix.platform }}
      runner: ${{ matrix.runner }}
      run-condition: ${{ needs.changed-files.outputs.should-run == 'true' && needs.require-label.outputs.result == 'true' }}
    secrets: inherit
