name: health-check

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  health-check:
    uses: ./.github/workflows/health-check-reusable.yaml
    secrets: inherit
