ARG AUTOWARE_DOCKER_ARCH
ARG AUTOWARE_TARGET_ARCH
ARG AUTOWARE_TARGET_PLATFORM
ARG AUTOWARE_DOCKER_DATE
ARG DOCKER_REPO
FROM ${DOCKER_REPO}:latest-${AUTOWARE_TARGET_PLATFORM}-kinetic-rosdep
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential
COPY files/FindCUDA.cmake /usr/share/cmake-3.5/Modules/FindCUDA.cmake
CMD . /opt/ros/kinetic/setup.sh && /bin/bash
